// Code generated by "enumer -type=ConnectionStatus -json -text -sql"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _ConnectionStatusName = "CONNECTINGUNSTABLEDISCONNECTEDRECONNECTING"

var _ConnectionStatusIndex = [...]uint8{0, 10, 18, 30, 42}

const _ConnectionStatusLowerName = "connectingunstabledisconnectedreconnecting"

func (i ConnectionStatus) String() string {
	if i < 0 || i >= ConnectionStatus(len(_ConnectionStatusIndex)-1) {
		return fmt.Sprintf("ConnectionStatus(%d)", i)
	}
	return _ConnectionStatusName[_ConnectionStatusIndex[i]:_ConnectionStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ConnectionStatusNoOp() {
	var x [1]struct{}
	_ = x[CONNECTING-(0)]
	_ = x[UNSTABLE-(1)]
	_ = x[DISCONNECTED-(2)]
	_ = x[RECONNECTING-(3)]
}

var _ConnectionStatusValues = []ConnectionStatus{CONNECTING, UNSTABLE, DISCONNECTED, RECONNECTING}

var _ConnectionStatusNameToValueMap = map[string]ConnectionStatus{
	_ConnectionStatusName[0:10]:       CONNECTING,
	_ConnectionStatusLowerName[0:10]:  CONNECTING,
	_ConnectionStatusName[10:18]:      UNSTABLE,
	_ConnectionStatusLowerName[10:18]: UNSTABLE,
	_ConnectionStatusName[18:30]:      DISCONNECTED,
	_ConnectionStatusLowerName[18:30]: DISCONNECTED,
	_ConnectionStatusName[30:42]:      RECONNECTING,
	_ConnectionStatusLowerName[30:42]: RECONNECTING,
}

var _ConnectionStatusNames = []string{
	_ConnectionStatusName[0:10],
	_ConnectionStatusName[10:18],
	_ConnectionStatusName[18:30],
	_ConnectionStatusName[30:42],
}

// ConnectionStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ConnectionStatusString(s string) (ConnectionStatus, error) {
	if val, ok := _ConnectionStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ConnectionStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ConnectionStatus values", s)
}

// ConnectionStatusValues returns all values of the enum
func ConnectionStatusValues() []ConnectionStatus {
	return _ConnectionStatusValues
}

// ConnectionStatusStrings returns a slice of all String values of the enum
func ConnectionStatusStrings() []string {
	strs := make([]string, len(_ConnectionStatusNames))
	copy(strs, _ConnectionStatusNames)
	return strs
}

// IsAConnectionStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ConnectionStatus) IsAConnectionStatus() bool {
	for _, v := range _ConnectionStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ConnectionStatus
func (i ConnectionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ConnectionStatus
func (i *ConnectionStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ConnectionStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ConnectionStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ConnectionStatus
func (i ConnectionStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ConnectionStatus
func (i *ConnectionStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = ConnectionStatusString(string(text))
	return err
}

func (i ConnectionStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ConnectionStatus) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ConnectionStatus: %[1]T(%[1]v)", value)
	}

	val, err := ConnectionStatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
