// Code generated by "enumer -type=DestinationStatus -json -text -sql"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _DestinationStatusName = "EditingConfirmDeleted"

var _DestinationStatusIndex = [...]uint8{0, 7, 14, 21}

const _DestinationStatusLowerName = "editingconfirmdeleted"

func (i DestinationStatus) String() string {
	if i < 0 || i >= DestinationStatus(len(_DestinationStatusIndex)-1) {
		return fmt.Sprintf("DestinationStatus(%d)", i)
	}
	return _DestinationStatusName[_DestinationStatusIndex[i]:_DestinationStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DestinationStatusNoOp() {
	var x [1]struct{}
	_ = x[Editing-(0)]
	_ = x[Confirm-(1)]
	_ = x[Deleted-(2)]
}

var _DestinationStatusValues = []DestinationStatus{Editing, Confirm, Deleted}

var _DestinationStatusNameToValueMap = map[string]DestinationStatus{
	_DestinationStatusName[0:7]:        Editing,
	_DestinationStatusLowerName[0:7]:   Editing,
	_DestinationStatusName[7:14]:       Confirm,
	_DestinationStatusLowerName[7:14]:  Confirm,
	_DestinationStatusName[14:21]:      Deleted,
	_DestinationStatusLowerName[14:21]: Deleted,
}

var _DestinationStatusNames = []string{
	_DestinationStatusName[0:7],
	_DestinationStatusName[7:14],
	_DestinationStatusName[14:21],
}

// DestinationStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DestinationStatusString(s string) (DestinationStatus, error) {
	if val, ok := _DestinationStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DestinationStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DestinationStatus values", s)
}

// DestinationStatusValues returns all values of the enum
func DestinationStatusValues() []DestinationStatus {
	return _DestinationStatusValues
}

// DestinationStatusStrings returns a slice of all String values of the enum
func DestinationStatusStrings() []string {
	strs := make([]string, len(_DestinationStatusNames))
	copy(strs, _DestinationStatusNames)
	return strs
}

// IsADestinationStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DestinationStatus) IsADestinationStatus() bool {
	for _, v := range _DestinationStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DestinationStatus
func (i DestinationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DestinationStatus
func (i *DestinationStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DestinationStatus should be a string, got %s", data)
	}

	var err error
	*i, err = DestinationStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for DestinationStatus
func (i DestinationStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DestinationStatus
func (i *DestinationStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = DestinationStatusString(string(text))
	return err
}

func (i DestinationStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *DestinationStatus) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of DestinationStatus: %[1]T(%[1]v)", value)
	}

	val, err := DestinationStatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
