// Code generated by "enumer -type=DriveStatus -json -text -sql"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _DriveStatusName = "OnROUTEDEVIATEDSTOPEMERGENCY"

var _DriveStatusIndex = [...]uint8{0, 7, 15, 19, 28}

const _DriveStatusLowerName = "onroutedeviatedstopemergency"

func (i DriveStatus) String() string {
	if i < 0 || i >= DriveStatus(len(_DriveStatusIndex)-1) {
		return fmt.Sprintf("DriveStatus(%d)", i)
	}
	return _DriveStatusName[_DriveStatusIndex[i]:_DriveStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DriveStatusNoOp() {
	var x [1]struct{}
	_ = x[OnROUTE-(0)]
	_ = x[DEVIATED-(1)]
	_ = x[STOP-(2)]
	_ = x[EMERGENCY-(3)]
}

var _DriveStatusValues = []DriveStatus{OnROUTE, DEVIATED, STOP, EMERGENCY}

var _DriveStatusNameToValueMap = map[string]DriveStatus{
	_DriveStatusName[0:7]:        OnROUTE,
	_DriveStatusLowerName[0:7]:   OnROUTE,
	_DriveStatusName[7:15]:       DEVIATED,
	_DriveStatusLowerName[7:15]:  DEVIATED,
	_DriveStatusName[15:19]:      STOP,
	_DriveStatusLowerName[15:19]: STOP,
	_DriveStatusName[19:28]:      EMERGENCY,
	_DriveStatusLowerName[19:28]: EMERGENCY,
}

var _DriveStatusNames = []string{
	_DriveStatusName[0:7],
	_DriveStatusName[7:15],
	_DriveStatusName[15:19],
	_DriveStatusName[19:28],
}

// DriveStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DriveStatusString(s string) (DriveStatus, error) {
	if val, ok := _DriveStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DriveStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DriveStatus values", s)
}

// DriveStatusValues returns all values of the enum
func DriveStatusValues() []DriveStatus {
	return _DriveStatusValues
}

// DriveStatusStrings returns a slice of all String values of the enum
func DriveStatusStrings() []string {
	strs := make([]string, len(_DriveStatusNames))
	copy(strs, _DriveStatusNames)
	return strs
}

// IsADriveStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DriveStatus) IsADriveStatus() bool {
	for _, v := range _DriveStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DriveStatus
func (i DriveStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DriveStatus
func (i *DriveStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DriveStatus should be a string, got %s", data)
	}

	var err error
	*i, err = DriveStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for DriveStatus
func (i DriveStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DriveStatus
func (i *DriveStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = DriveStatusString(string(text))
	return err
}

func (i DriveStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *DriveStatus) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of DriveStatus: %[1]T(%[1]v)", value)
	}

	val, err := DriveStatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
