// Code generated by "enumer -type=GroupRole -json -text -sql -trimprefix=GroupRole -transform=lower"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _GroupRoleName = "owneradminmember"

var _GroupRoleIndex = [...]uint8{0, 5, 10, 16}

const _GroupRoleLowerName = "owneradminmember"

func (i GroupRole) String() string {
	if i < 0 || i >= GroupRole(len(_GroupRoleIndex)-1) {
		return fmt.Sprintf("GroupRole(%d)", i)
	}
	return _GroupRoleName[_GroupRoleIndex[i]:_GroupRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GroupRoleNoOp() {
	var x [1]struct{}
	_ = x[GroupRoleOwner-(0)]
	_ = x[GroupRoleAdmin-(1)]
	_ = x[GroupRoleMember-(2)]
}

var _GroupRoleValues = []GroupRole{GroupRoleOwner, GroupRoleAdmin, GroupRoleMember}

var _GroupRoleNameToValueMap = map[string]GroupRole{
	_GroupRoleName[0:5]:        GroupRoleOwner,
	_GroupRoleLowerName[0:5]:   GroupRoleOwner,
	_GroupRoleName[5:10]:       GroupRoleAdmin,
	_GroupRoleLowerName[5:10]:  GroupRoleAdmin,
	_GroupRoleName[10:16]:      GroupRoleMember,
	_GroupRoleLowerName[10:16]: GroupRoleMember,
}

var _GroupRoleNames = []string{
	_GroupRoleName[0:5],
	_GroupRoleName[5:10],
	_GroupRoleName[10:16],
}

// GroupRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GroupRoleString(s string) (GroupRole, error) {
	if val, ok := _GroupRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GroupRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GroupRole values", s)
}

// GroupRoleValues returns all values of the enum
func GroupRoleValues() []GroupRole {
	return _GroupRoleValues
}

// GroupRoleStrings returns a slice of all String values of the enum
func GroupRoleStrings() []string {
	strs := make([]string, len(_GroupRoleNames))
	copy(strs, _GroupRoleNames)
	return strs
}

// IsAGroupRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GroupRole) IsAGroupRole() bool {
	for _, v := range _GroupRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for GroupRole
func (i GroupRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for GroupRole
func (i *GroupRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("GroupRole should be a string, got %s", data)
	}

	var err error
	*i, err = GroupRoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for GroupRole
func (i GroupRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for GroupRole
func (i *GroupRole) UnmarshalText(text []byte) error {
	var err error
	*i, err = GroupRoleString(string(text))
	return err
}

func (i GroupRole) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *GroupRole) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of GroupRole: %[1]T(%[1]v)", value)
	}

	val, err := GroupRoleString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
