// Code generated by "enumer -type=LegSource -json -text -sql -trimprefix=LegSource -transform=lower"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _LegSourceName = "directiontrip"

var _LegSourceIndex = [...]uint8{0, 9, 13}

const _LegSourceLowerName = "directiontrip"

func (i LegSource) String() string {
	if i < 0 || i >= LegSource(len(_LegSourceIndex)-1) {
		return fmt.Sprintf("LegSource(%d)", i)
	}
	return _LegSourceName[_LegSourceIndex[i]:_LegSourceIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LegSourceNoOp() {
	var x [1]struct{}
	_ = x[LegSourceDirection-(0)]
	_ = x[LegSourceTrip-(1)]
}

var _LegSourceValues = []LegSource{LegSourceDirection, LegSourceTrip}

var _LegSourceNameToValueMap = map[string]LegSource{
	_LegSourceName[0:9]:       LegSourceDirection,
	_LegSourceLowerName[0:9]:  LegSourceDirection,
	_LegSourceName[9:13]:      LegSourceTrip,
	_LegSourceLowerName[9:13]: LegSourceTrip,
}

var _LegSourceNames = []string{
	_LegSourceName[0:9],
	_LegSourceName[9:13],
}

// LegSourceString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LegSourceString(s string) (LegSource, error) {
	if val, ok := _LegSourceNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LegSourceNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LegSource values", s)
}

// LegSourceValues returns all values of the enum
func LegSourceValues() []LegSource {
	return _LegSourceValues
}

// LegSourceStrings returns a slice of all String values of the enum
func LegSourceStrings() []string {
	strs := make([]string, len(_LegSourceNames))
	copy(strs, _LegSourceNames)
	return strs
}

// IsALegSource returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LegSource) IsALegSource() bool {
	for _, v := range _LegSourceValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LegSource
func (i LegSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LegSource
func (i *LegSource) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LegSource should be a string, got %s", data)
	}

	var err error
	*i, err = LegSourceString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for LegSource
func (i LegSource) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LegSource
func (i *LegSource) UnmarshalText(text []byte) error {
	var err error
	*i, err = LegSourceString(string(text))
	return err
}

func (i LegSource) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *LegSource) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of LegSource: %[1]T(%[1]v)", value)
	}

	val, err := LegSourceString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
