// Code generated by "enumer -type=MembershipStatus -json -text -sql -trimprefix=Membership -transform=lower"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _MembershipStatusName = "invitedpendingactiverejectedleftkicked"

var _MembershipStatusIndex = [...]uint8{0, 7, 14, 20, 28, 32, 38}

const _MembershipStatusLowerName = "invitedpendingactiverejectedleftkicked"

func (i MembershipStatus) String() string {
	if i < 0 || i >= MembershipStatus(len(_MembershipStatusIndex)-1) {
		return fmt.Sprintf("MembershipStatus(%d)", i)
	}
	return _MembershipStatusName[_MembershipStatusIndex[i]:_MembershipStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MembershipStatusNoOp() {
	var x [1]struct{}
	_ = x[MembershipInvited-(0)]
	_ = x[MembershipPending-(1)]
	_ = x[MembershipActive-(2)]
	_ = x[MembershipRejected-(3)]
	_ = x[MembershipLeft-(4)]
	_ = x[MembershipKicked-(5)]
}

var _MembershipStatusValues = []MembershipStatus{MembershipInvited, MembershipPending, MembershipActive, MembershipRejected, MembershipLeft, MembershipKicked}

var _MembershipStatusNameToValueMap = map[string]MembershipStatus{
	_MembershipStatusName[0:7]:        MembershipInvited,
	_MembershipStatusLowerName[0:7]:   MembershipInvited,
	_MembershipStatusName[7:14]:       MembershipPending,
	_MembershipStatusLowerName[7:14]:  MembershipPending,
	_MembershipStatusName[14:20]:      MembershipActive,
	_MembershipStatusLowerName[14:20]: MembershipActive,
	_MembershipStatusName[20:28]:      MembershipRejected,
	_MembershipStatusLowerName[20:28]: MembershipRejected,
	_MembershipStatusName[28:32]:      MembershipLeft,
	_MembershipStatusLowerName[28:32]: MembershipLeft,
	_MembershipStatusName[32:38]:      MembershipKicked,
	_MembershipStatusLowerName[32:38]: MembershipKicked,
}

var _MembershipStatusNames = []string{
	_MembershipStatusName[0:7],
	_MembershipStatusName[7:14],
	_MembershipStatusName[14:20],
	_MembershipStatusName[20:28],
	_MembershipStatusName[28:32],
	_MembershipStatusName[32:38],
}

// MembershipStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MembershipStatusString(s string) (MembershipStatus, error) {
	if val, ok := _MembershipStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MembershipStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MembershipStatus values", s)
}

// MembershipStatusValues returns all values of the enum
func MembershipStatusValues() []MembershipStatus {
	return _MembershipStatusValues
}

// MembershipStatusStrings returns a slice of all String values of the enum
func MembershipStatusStrings() []string {
	strs := make([]string, len(_MembershipStatusNames))
	copy(strs, _MembershipStatusNames)
	return strs
}

// IsAMembershipStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MembershipStatus) IsAMembershipStatus() bool {
	for _, v := range _MembershipStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MembershipStatus
func (i MembershipStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MembershipStatus
func (i *MembershipStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MembershipStatus should be a string, got %s", data)
	}

	var err error
	*i, err = MembershipStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for MembershipStatus
func (i MembershipStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MembershipStatus
func (i *MembershipStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = MembershipStatusString(string(text))
	return err
}

func (i MembershipStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *MembershipStatus) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of MembershipStatus: %[1]T(%[1]v)", value)
	}

	val, err := MembershipStatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
