// Code generated by "enumer -type=TripType -json -text -sql -trimprefix=TripType -transform=lower"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _TripTypeName = "bronzesilvergolddiamond"

var _TripTypeIndex = [...]uint8{0, 6, 12, 16, 23}

const _TripTypeLowerName = "bronzesilvergolddiamond"

func (i TripType) String() string {
	if i < 0 || i >= TripType(len(_TripTypeIndex)-1) {
		return fmt.Sprintf("TripType(%d)", i)
	}
	return _TripTypeName[_TripTypeIndex[i]:_TripTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TripTypeNoOp() {
	var x [1]struct{}
	_ = x[TripTypeBronze-(0)]
	_ = x[TripTypeSilver-(1)]
	_ = x[TripTypeGold-(2)]
	_ = x[TripTypeDiamond-(3)]
}

var _TripTypeValues = []TripType{TripTypeBronze, TripTypeSilver, TripTypeGold, TripTypeDiamond}

var _TripTypeNameToValueMap = map[string]TripType{
	_TripTypeName[0:6]:        TripTypeBronze,
	_TripTypeLowerName[0:6]:   TripTypeBronze,
	_TripTypeName[6:12]:       TripTypeSilver,
	_TripTypeLowerName[6:12]:  TripTypeSilver,
	_TripTypeName[12:16]:      TripTypeGold,
	_TripTypeLowerName[12:16]: TripTypeGold,
	_TripTypeName[16:23]:      TripTypeDiamond,
	_TripTypeLowerName[16:23]: TripTypeDiamond,
}

var _TripTypeNames = []string{
	_TripTypeName[0:6],
	_TripTypeName[6:12],
	_TripTypeName[12:16],
	_TripTypeName[16:23],
}

// TripTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TripTypeString(s string) (TripType, error) {
	if val, ok := _TripTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TripTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TripType values", s)
}

// TripTypeValues returns all values of the enum
func TripTypeValues() []TripType {
	return _TripTypeValues
}

// TripTypeStrings returns a slice of all String values of the enum
func TripTypeStrings() []string {
	strs := make([]string, len(_TripTypeNames))
	copy(strs, _TripTypeNames)
	return strs
}

// IsATripType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TripType) IsATripType() bool {
	for _, v := range _TripTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TripType
func (i TripType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TripType
func (i *TripType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TripType should be a string, got %s", data)
	}

	var err error
	*i, err = TripTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TripType
func (i TripType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TripType
func (i *TripType) UnmarshalText(text []byte) error {
	var err error
	*i, err = TripTypeString(string(text))
	return err
}

func (i TripType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *TripType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of TripType: %[1]T(%[1]v)", value)
	}

	val, err := TripTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
