// Code generated by "enumer -type=TripRole -json -text -sql -trimprefix=TripRole -transform=lower"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _TripRoleName = "leadermember"

var _TripRoleIndex = [...]uint8{0, 6, 12}

const _TripRoleLowerName = "leadermember"

func (i TripRole) String() string {
	if i < 0 || i >= TripRole(len(_TripRoleIndex)-1) {
		return fmt.Sprintf("TripRole(%d)", i)
	}
	return _TripRoleName[_TripRoleIndex[i]:_TripRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TripRoleNoOp() {
	var x [1]struct{}
	_ = x[TripRoleLeader-(0)]
	_ = x[TripRoleMember-(1)]
}

var _TripRoleValues = []TripRole{TripRoleLeader, TripRoleMember}

var _TripRoleNameToValueMap = map[string]TripRole{
	_TripRoleName[0:6]:       TripRoleLeader,
	_TripRoleLowerName[0:6]:  TripRoleLeader,
	_TripRoleName[6:12]:      TripRoleMember,
	_TripRoleLowerName[6:12]: TripRoleMember,
}

var _TripRoleNames = []string{
	_TripRoleName[0:6],
	_TripRoleName[6:12],
}

// TripRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TripRoleString(s string) (TripRole, error) {
	if val, ok := _TripRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TripRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TripRole values", s)
}

// TripRoleValues returns all values of the enum
func TripRoleValues() []TripRole {
	return _TripRoleValues
}

// TripRoleStrings returns a slice of all String values of the enum
func TripRoleStrings() []string {
	strs := make([]string, len(_TripRoleNames))
	copy(strs, _TripRoleNames)
	return strs
}

// IsATripRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TripRole) IsATripRole() bool {
	for _, v := range _TripRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TripRole
func (i TripRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TripRole
func (i *TripRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TripRole should be a string, got %s", data)
	}

	var err error
	*i, err = TripRoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TripRole
func (i TripRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TripRole
func (i *TripRole) UnmarshalText(text []byte) error {
	var err error
	*i, err = TripRoleString(string(text))
	return err
}

func (i TripRole) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *TripRole) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of TripRole: %[1]T(%[1]v)", value)
	}

	val, err := TripRoleString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
