// Code generated by "enumer -type=TripStatus -json -text -sql -trimprefix=Trip -transform=lower"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _TripStatusName = "planninglocked"

var _TripStatusIndex = [...]uint8{0, 8, 14}

const _TripStatusLowerName = "planninglocked"

func (i TripStatus) String() string {
	if i < 0 || i >= TripStatus(len(_TripStatusIndex)-1) {
		return fmt.Sprintf("TripStatus(%d)", i)
	}
	return _TripStatusName[_TripStatusIndex[i]:_TripStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TripStatusNoOp() {
	var x [1]struct{}
	_ = x[TripPlanning-(0)]
	_ = x[TripLocked-(1)]
}

var _TripStatusValues = []TripStatus{TripPlanning, TripLocked}

var _TripStatusNameToValueMap = map[string]TripStatus{
	_TripStatusName[0:8]:       TripPlanning,
	_TripStatusLowerName[0:8]:  TripPlanning,
	_TripStatusName[8:14]:      TripLocked,
	_TripStatusLowerName[8:14]: TripLocked,
}

var _TripStatusNames = []string{
	_TripStatusName[0:8],
	_TripStatusName[8:14],
}

// TripStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TripStatusString(s string) (TripStatus, error) {
	if val, ok := _TripStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TripStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TripStatus values", s)
}

// TripStatusValues returns all values of the enum
func TripStatusValues() []TripStatus {
	return _TripStatusValues
}

// TripStatusStrings returns a slice of all String values of the enum
func TripStatusStrings() []string {
	strs := make([]string, len(_TripStatusNames))
	copy(strs, _TripStatusNames)
	return strs
}

// IsATripStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TripStatus) IsATripStatus() bool {
	for _, v := range _TripStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TripStatus
func (i TripStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TripStatus
func (i *TripStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TripStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TripStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TripStatus
func (i TripStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TripStatus
func (i *TripStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = TripStatusString(string(text))
	return err
}

func (i TripStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *TripStatus) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of TripStatus: %[1]T(%[1]v)", value)
	}

	val, err := TripStatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
