// Code generated by "enumer -type=Vehicle"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _VehicleName = "VehicleUnknownCARBIKETRUCKTAXIHD"

var _VehicleIndex = [...]uint8{0, 14, 17, 21, 26, 30, 32}

const _VehicleLowerName = "vehicleunknowncarbiketrucktaxihd"

func (i Vehicle) String() string {
	if i >= Vehicle(len(_VehicleIndex)-1) {
		return fmt.Sprintf("Vehicle(%d)", i)
	}
	return _VehicleName[_VehicleIndex[i]:_VehicleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _VehicleNoOp() {
	var x [1]struct{}
	_ = x[VehicleUnknown-(0)]
	_ = x[CAR-(1)]
	_ = x[BIKE-(2)]
	_ = x[TRUCK-(3)]
	_ = x[TAXI-(4)]
	_ = x[HD-(5)]
}

var _VehicleValues = []Vehicle{VehicleUnknown, CAR, BIKE, TRUCK, TAXI, HD}

var _VehicleNameToValueMap = map[string]Vehicle{
	_VehicleName[0:14]:       VehicleUnknown,
	_VehicleLowerName[0:14]:  VehicleUnknown,
	_VehicleName[14:17]:      CAR,
	_VehicleLowerName[14:17]: CAR,
	_VehicleName[17:21]:      BIKE,
	_VehicleLowerName[17:21]: BIKE,
	_VehicleName[21:26]:      TRUCK,
	_VehicleLowerName[21:26]: TRUCK,
	_VehicleName[26:30]:      TAXI,
	_VehicleLowerName[26:30]: TAXI,
	_VehicleName[30:32]:      HD,
	_VehicleLowerName[30:32]: HD,
}

var _VehicleNames = []string{
	_VehicleName[0:14],
	_VehicleName[14:17],
	_VehicleName[17:21],
	_VehicleName[21:26],
	_VehicleName[26:30],
	_VehicleName[30:32],
}

// VehicleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VehicleString(s string) (Vehicle, error) {
	if val, ok := _VehicleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _VehicleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Vehicle values", s)
}

// VehicleValues returns all values of the enum
func VehicleValues() []Vehicle {
	return _VehicleValues
}

// VehicleStrings returns a slice of all String values of the enum
func VehicleStrings() []string {
	strs := make([]string, len(_VehicleNames))
	copy(strs, _VehicleNames)
	return strs
}

// IsAVehicle returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Vehicle) IsAVehicle() bool {
	for _, v := range _VehicleValues {
		if i == v {
			return true
		}
	}
	return false
}
