package repository

import "errors"

var (
	ErrMemberRoleNotInCache      = errors.New("member role not found in cache")
	ErrUserNotTripMember         = errors.New("user is not an active trip member")
	ErrTripNotFound              = errors.New("trip not found")
	ErrUserNotFound              = errors.New("user not found")
	ErrNoTripUpdate              = errors.New("no fields to update")
	ErrNoTripMemberUpdate        = errors.New("no fields to update on the member")
	ErrTripMembersRequired       = errors.New("at least one member besides the leader is required")
	ErrTripMemberLimit           = errors.New("trip member limit reached")
	ErrTripTypePolicyUnset       = errors.New("member limit policy is not set for this trip type")
	ErrAlreadyTripMember         = errors.New("user is already a trip member")
	ErrAlreadyInvited            = errors.New("user is already invited to this trip")
	ErrJoinRequestPending        = errors.New("user already has a pending join request")
	ErrInvitationNotFound        = errors.New("invitation not found")
	ErrInvitationNotPending      = errors.New("membership is not a pending invitation")
	ErrJoinRequestNotFound       = errors.New("join request not found")
	ErrJoinRequestNotPending     = errors.New("membership is not a pending join request")
	ErrCannotInviteSelf          = errors.New("cannot invite yourself")
	ErrCannotKickLeader          = errors.New("cannot kick the trip leader")
	ErrCannotKickSelf            = errors.New("cannot kick yourself")
	ErrInsufficientKickRole      = errors.New("insufficient role to kick this member")
	ErrCannotUpdateOtherNickname = errors.New("can only update your own nickname")
	ErrCannotChangeLeaderRole    = errors.New("cannot change the leader role")
	ErrInviteNotFound            = errors.New("invite link not found")
	ErrNoSuccessorToTransfer     = errors.New("no member to transfer leadership to")
	ErrInternalServerError       = errors.New("internal server error")
	ErrDestinationNotFound       = errors.New("destination not found")
	ErrDestinationNotEditing     = errors.New("destination is not editing")
	ErrDestinationInUse          = errors.New("destination is still used by a trip that is not planning")
	ErrLocationNotFound          = errors.New("location not found")
	ErrInvalidTripGraph          = errors.New("invalid trip graph")
	ErrBranchNotFound            = errors.New("branch not found")
	ErrBranchStopNotFound        = errors.New("branch stop not found")
	ErrDraftBranchExcluded       = errors.New("draft branch is excluded from the route")
	ErrNoBranchStopUpdate        = errors.New("no fields to update on the branch stop")
)
