// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/user/forget-password": {
            "post": {
                "description": "If the email exists, send a reset-password HTML mail with a one-time link.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Forget password",
                "parameters": [
                    {
                        "description": "Forget password payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ForgetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ForgetPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/user/login": {
            "post": {
                "description": "Authenticate with username and password. Returns access and refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.LoginEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/user/logout": {
            "post": {
                "description": "Revoke the presented refresh token. The SHA-256 hash is stored in Redis with TTL until JWT exp, and persisted in Postgres so a Redis restart cannot revive the session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "Refresh token to revoke",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.LogoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/user/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Return the authenticated user. Password hash is never included.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "My profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/user/refresh": {
            "post": {
                "description": "Issue a new access token from a valid refresh token. Returns 401 if the refresh JWT is expired or was revoked by logout.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RefreshResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/user/register": {
            "post": {
                "description": "Create a user account. Returns the new user UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/user/reset-password/{resetToken}": {
            "post": {
                "description": "Set a new password using the reset token from the forget-password mail.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reset JWT from mail",
                        "name": "resetToken",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResetPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/user/{id}": {
            "get": {
                "description": "Return a user by UUID. Password hash is never included.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get user profile",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goong/directions": {
            "get": {
                "security": [
                    {
                        "PlaygroundKey": []
                    }
                ],
                "description": "Goong Directions v2. Default vehicle is bike (two-wheeler / motorbike lanes). motorcycle and motorbike are aliased to bike.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goong"
                ],
                "summary": "Route A to B",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Origin lat,lng",
                        "name": "origin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination lat,lng (semicolon-separated for extra stops)",
                        "name": "destination",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "car, bike, taxi, truck, hd. motorbike/motorcycle → bike",
                        "name": "vehicle",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Return alternatives; skips Leg cache",
                        "name": "alternatives",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Leg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goong/geocode": {
            "get": {
                "security": [
                    {
                        "PlaygroundKey": []
                    }
                ],
                "description": "Goong Geocode v2. Provide exactly one of address (forward), latlng (reverse), or place_id. Default results use the new administrative units. has_deprecated_administrative_unit=true adds pre-merger names. has_vnid=true adds deprecated_compound_id on reverse.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goong"
                ],
                "summary": "Geocode address or coordinates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Forward: address to coordinates",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Reverse: lat,lng to address",
                        "name": "latlng",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Lookup by Goong place_id",
                        "name": "place_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (reverse)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "true = also return deprecated_description / deprecated_compound",
                        "name": "has_deprecated_administrative_unit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "true = also return deprecated_compound_id (VN admin codes)",
                        "name": "has_vnid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GeocodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goong/places/autocomplete": {
            "get": {
                "security": [
                    {
                        "PlaygroundKey": []
                    }
                ],
                "description": "Goong Place Autocomplete v2. location biases the search; origin (lat,lng) sorts by proximity and fills distance_meters. If origin is omitted, location is reused. Set has_deprecated_administrative_unit=true to also get pre-merger names.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goong"
                ],
                "summary": "Autocomplete places",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "input",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bias as lat,lng",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by distance from this lat,lng. Defaults to location",
                        "name": "origin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max predictions",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Search radius in km from location. Goong default 50",
                        "name": "radius",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "true = also return deprecated_description / deprecated_compound",
                        "name": "has_deprecated_administrative_unit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AutocompleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goong/places/detail": {
            "get": {
                "security": [
                    {
                        "PlaygroundKey": []
                    }
                ],
                "description": "Goong Place Detail v2 by place_id. Default address is the new administrative unit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goong"
                ],
                "summary": "Place detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Goong place_id",
                        "name": "place_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "true = also return deprecated_description / deprecated_compound",
                        "name": "has_deprecated_administrative_unit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PlaceDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goong/trips": {
            "get": {
                "security": [
                    {
                        "PlaygroundKey": []
                    }
                ],
                "description": "Goong Trip v2 is a single-vehicle TSP, not a branch graph. waypoints is a bag of lat,lng points (semicolon-separated), not an edge list. The waypoints array stays in input order; waypoint_index / visit_order is the visit sequence on that one tour. trips_index is copied from OSRM and is 0 unless Goong returns several tours — it does not mean a split at a shared vertex.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goong"
                ],
                "summary": "Optimize multi-stop trip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start lat,lng. If omitted Goong picks a stop.",
                        "name": "origin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End lat,lng. If omitted Goong picks a stop.",
                        "name": "destination",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Stops between origin and destination, lat,lng separated by ;",
                        "name": "waypoints",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "car, bike, taxi, truck, hd. Default car. motorbike/motorcycle → bike",
                        "name": "vehicle",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Return to start. Default true",
                        "name": "roundtrip",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Turn-by-turn per leg. Default true (Goong/OSRM default is false, which yields empty steps)",
                        "name": "steps",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Road-To-Destination-BE_module_maps_model.Trip"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns groups where the caller is an active member (owner, admin, or member). Each item includes myRole. Invited/pending/left/kicked memberships are omitted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "List my groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GroupListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a standing group. The caller becomes owner (active). Optional adminUsernames are added immediately as active admins. Unknown usernames abort the whole create. Roles: owner, admin, member. Membership statuses: invited, pending, active, rejected, left, kicked.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Create group",
                "parameters": [
                    {
                        "description": "Group name, optional description, optional admin usernames",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.GroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/invitations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns invitations waiting for the caller to accept or reject. Other users' invitations are never included.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "List my group invitations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.InvitationListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/mine": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns groups where the caller is an active member (owner, admin, or member). Each item includes myRole.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "List groups I have joined",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GroupListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{groupId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns name and description. If the caller is an active member, myRole is set (owner/admin/member). Non-members still receive public name/description so they can request to join; roster is never included here.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Get group",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Owner only. Fails with 409 if the group still has trips (trips.group_id). Members cascade-delete with the group.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Delete group",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Group deleted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Owner or admin may change name and/or description. Members cannot update group info. Send only the fields to change.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Update group",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{groupId}/invitations": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The invited caller accepts or rejects with ?action=accept|reject. Accept makes them an active member; reject sets status rejected.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Respond to a group invitation",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "accept",
                            "reject"
                        ],
                        "type": "string",
                        "description": "accept or reject",
                        "name": "action",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.InvitationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{groupId}/invite/{userId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Owner or admin invites a user by UUID. Reuses a left/rejected/kicked membership row. The invitee later accepts or rejects.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Invite a user to a group",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Invitee UUID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.InvitationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{groupId}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The caller creates a pending join request. Owner/admin later accept or reject it. Reuses a left/rejected/kicked membership row.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Request to join a group",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.InvitationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{groupId}/join-requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Owner or admin lists users waiting to join this group.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "List pending join requests",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.JoinRequestListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{groupId}/join-requests/{userId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Owner or admin responds with ?action=accept|reject. Accept makes the user an active member; reject sets status rejected.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Accept or reject a join request",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Group UUID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Applicant UUID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "accept",
                            "reject"
                        ],
                        "type": "string",
                        "description": "accept or reject",
                        "name": "action",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.InvitationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Road-To-Destination-BE_module_maps_model.Trip": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "computed_at": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "roundtrip": {
                    "type": "boolean"
                },
                "trips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripRoute"
                    }
                },
                "vehicle": {
                    "type": "string",
                    "example": "car"
                },
                "visit_order": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripStop"
                    }
                },
                "waypoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripStop"
                    }
                }
            }
        },
        "model.LatLng": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "model.Leg": {
            "type": "object",
            "properties": {
                "createdTime": {
                    "type": "string"
                },
                "distanceM": {
                    "type": "number"
                },
                "durationS": {
                    "type": "number"
                },
                "fromLat": {
                    "type": "number"
                },
                "fromLng": {
                    "type": "number"
                },
                "fromLocationId": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "lastComputedAt": {
                    "type": "string"
                },
                "polyline": {
                    "type": "string"
                },
                "source": {
                    "type": "string",
                    "example": "direction"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.RouteStep"
                    }
                },
                "toLat": {
                    "type": "number"
                },
                "toLng": {
                    "type": "number"
                },
                "toLocationId": {
                    "type": "string"
                },
                "ttlSeconds": {
                    "type": "integer"
                },
                "updatedTime": {
                    "type": "string"
                },
                "vehicle": {
                    "type": "string",
                    "example": "bike"
                }
            }
        },
        "model.RouteStep": {
            "type": "object",
            "properties": {
                "distanceM": {
                    "type": "number"
                },
                "durationS": {
                    "type": "number"
                },
                "endLat": {
                    "type": "number"
                },
                "endLng": {
                    "type": "number"
                },
                "instruction": {
                    "type": "string"
                },
                "maneuver": {
                    "type": "string"
                },
                "polyline": {
                    "type": "string"
                },
                "startLat": {
                    "type": "number"
                },
                "startLng": {
                    "type": "number"
                },
                "travelMode": {
                    "type": "string"
                }
            }
        },
        "model.TripLeg": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "duration": {
                    "type": "number"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripStep"
                    }
                },
                "summary": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "model.TripRoute": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "duration": {
                    "type": "number"
                },
                "geometry": {
                    "type": "string"
                },
                "legs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripLeg"
                    }
                },
                "weight": {
                    "type": "number"
                },
                "weight_name": {
                    "type": "string"
                }
            }
        },
        "model.TripStep": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "duration": {
                    "type": "number"
                },
                "geometry": {
                    "type": "string"
                },
                "instruction": {
                    "type": "string"
                },
                "maneuver": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "model.TripStop": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "input_index": {
                    "type": "integer"
                },
                "location": {
                    "$ref": "#/definitions/model.LatLng"
                },
                "place_id": {
                    "type": "string"
                },
                "trips_index": {
                    "type": "integer"
                },
                "waypoint_index": {
                    "type": "integer"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "createdTime": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "updatedTime": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.CreateGroupRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "adminUsernames": {
                    "type": "array",
                    "maxItems": 50,
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string",
                    "maxLength": 4000
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "request.ForgetPasswordRequest": {
            "type": "object",
            "required": [
                "mail"
            ],
            "properties": {
                "mail": {
                    "type": "string"
                }
            }
        },
        "request.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 4
                }
            }
        },
        "request.LogoutRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "request.RefreshRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "required": [
                "confirmPassword",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 4
                }
            }
        },
        "request.ResetPasswordRequest": {
            "type": "object",
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "request.UpdateGroupRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 4000
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "response.AddressComponent": {
            "type": "object",
            "properties": {
                "long_name": {
                    "type": "string"
                },
                "short_name": {
                    "type": "string"
                }
            }
        },
        "response.AdministrativeCompound": {
            "type": "object",
            "properties": {
                "commune": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                }
            }
        },
        "response.AdministrativeCompoundID": {
            "type": "object",
            "properties": {
                "commune": {
                    "type": "integer"
                },
                "district": {
                    "type": "integer"
                },
                "province": {
                    "type": "integer"
                }
            }
        },
        "response.AutocompleteResponse": {
            "type": "object",
            "properties": {
                "execution_time": {
                    "type": "string"
                },
                "predictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PlacePrediction"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.ForgetPasswordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.GeocodeGeometry": {
            "type": "object",
            "properties": {
                "boundary": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/response.LatLng"
                }
            }
        },
        "response.GeocodeResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.GeocodeResult"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.GeocodeResult": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "address_components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AddressComponent"
                    }
                },
                "compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_compound_id": {
                    "$ref": "#/definitions/response.AdministrativeCompoundID"
                },
                "deprecated_description": {
                    "type": "string"
                },
                "formatted_address": {
                    "type": "string"
                },
                "geometry": {
                    "$ref": "#/definitions/response.GeocodeGeometry"
                },
                "name": {
                    "type": "string"
                },
                "place_id": {
                    "type": "string"
                },
                "plus_code": {
                    "$ref": "#/definitions/response.PlusCode"
                },
                "reference": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.GroupListResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.GroupResponse"
                    }
                }
            }
        },
        "response.GroupResponse": {
            "type": "object",
            "properties": {
                "createdTime": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "myRole": {
                    "type": "string",
                    "example": "owner"
                },
                "name": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string",
                    "format": "uuid"
                },
                "updatedTime": {
                    "type": "string"
                }
            }
        },
        "response.InvitationListResponse": {
            "type": "object",
            "properties": {
                "invitations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.InvitationResponse"
                    }
                }
            }
        },
        "response.InvitationResponse": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "string",
                    "format": "uuid"
                },
                "groupName": {
                    "type": "string"
                },
                "invitorName": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "invited"
                },
                "userId": {
                    "type": "string",
                    "format": "uuid"
                },
                "userName": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string",
                    "example": "member"
                }
            }
        },
        "response.JoinRequestListResponse": {
            "type": "object",
            "properties": {
                "joinRequests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.InvitationResponse"
                    }
                }
            }
        },
        "response.LatLng": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "response.LoginEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.LoginResponse"
                }
            }
        },
        "response.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "response.LogoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "logged out"
                }
            }
        },
        "response.MatchedSubstring": {
            "type": "object",
            "properties": {
                "length": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "response.PlaceDetail": {
            "type": "object",
            "properties": {
                "compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_description": {
                    "type": "string"
                },
                "formatted_address": {
                    "type": "string"
                },
                "geometry": {
                    "$ref": "#/definitions/response.PlaceGeometry"
                },
                "name": {
                    "type": "string"
                },
                "place_id": {
                    "type": "string"
                }
            }
        },
        "response.PlaceDetailResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/response.PlaceDetail"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.PlaceGeometry": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/response.LatLng"
                }
            }
        },
        "response.PlacePrediction": {
            "type": "object",
            "properties": {
                "compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_description": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "distance_meters": {
                    "type": "integer"
                },
                "has_children": {
                    "type": "boolean"
                },
                "matched_substrings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MatchedSubstring"
                    }
                },
                "place_id": {
                    "type": "string"
                },
                "plus_code": {
                    "$ref": "#/definitions/response.PlusCode"
                },
                "reference": {
                    "type": "string"
                },
                "structured_formatting": {
                    "$ref": "#/definitions/response.StructuredFormatting"
                },
                "terms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PlaceTerm"
                    }
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.PlaceTerm": {
            "type": "object",
            "properties": {
                "offset": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "response.PlusCode": {
            "type": "object",
            "properties": {
                "compound_code": {
                    "type": "string"
                },
                "global_code": {
                    "type": "string"
                }
            }
        },
        "response.RefreshResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "response.RegisterResponse": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "response.ResetPasswordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.StructuredFormatting": {
            "type": "object",
            "properties": {
                "main_text": {
                    "type": "string"
                },
                "main_text_matched_substrings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MatchedSubstring"
                    }
                },
                "secondary_text": {
                    "type": "string"
                },
                "secondary_text_matched_substrings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MatchedSubstring"
                    }
                }
            }
        },
        "share.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "invalid input"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "PlaygroundKey": {
            "description": "Shared secret from GOONG_PLAYGROUND_KEY. Scalar → Authorize.",
            "type": "apiKey",
            "name": "X-Playground-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Road2D",
	Description:      "Backend API for Road2D (team Vandra): collaborative multi-branch ride planning and group-ride safety in Vietnam. JWT auth, Goong Maps playground, trip graph models.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
