// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/directions": {
            "get": {
                "description": "Goong Directions v2. Default vehicle is bike (two-wheeler / motorbike lanes). motorcycle and motorbike are aliased to bike.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maps"
                ],
                "summary": "Route A to B",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Origin lat,lng",
                        "name": "origin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination lat,lng (semicolon-separated for extra stops)",
                        "name": "destination",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "car, bike, taxi, truck, hd. motorbike/motorcycle → bike",
                        "name": "vehicle",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Return alternatives; skips LocationLeg cache",
                        "name": "alternatives",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LocationLeg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/places/autocomplete": {
            "get": {
                "description": "Goong Place Autocomplete v2. Default returns new administrative units. Set has_deprecated_administrative_unit=true to also get pre-merger names.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maps"
                ],
                "summary": "Autocomplete places",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "input",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bias as lat,lng",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max predictions",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "true = also return deprecated_description / deprecated_compound",
                        "name": "has_deprecated_administrative_unit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AutocompleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/places/detail": {
            "get": {
                "description": "Goong Place Detail v2 by place_id. Default address is the new administrative unit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maps"
                ],
                "summary": "Place detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Goong place_id",
                        "name": "place_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "true = also return deprecated_description / deprecated_compound",
                        "name": "has_deprecated_administrative_unit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PlaceDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/trips": {
            "get": {
                "description": "Goong Trip v2. Combines routing with stop-order optimization. origin, waypoints, and destination are each optional but together need ≥10 coordinates. Default vehicle is car. roundtrip defaults true (origin and destination must differ). waypoint_index is the optimized visit order; location is the point snapped to the road.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maps"
                ],
                "summary": "Optimize multi-stop trip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start lat,lng. If omitted Goong picks a stop.",
                        "name": "origin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End lat,lng. If omitted Goong picks a stop.",
                        "name": "destination",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Stops between origin and destination, lat,lng separated by ;",
                        "name": "waypoints",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "car, bike, taxi, truck, hd. Default car. motorbike/motorcycle → bike",
                        "name": "vehicle",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Return to start. Default true",
                        "name": "roundtrip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Trip"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/share.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.LatLng": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "model.LocationLeg": {
            "type": "object",
            "properties": {
                "computed_at": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "distance_m": {
                    "type": "integer"
                },
                "duration_s": {
                    "type": "integer"
                },
                "origin": {
                    "type": "string"
                },
                "polyline": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.RouteStep"
                    }
                },
                "vehicle": {
                    "type": "string",
                    "example": "bike"
                }
            }
        },
        "model.RouteStep": {
            "type": "object",
            "properties": {
                "distance_m": {
                    "type": "integer"
                },
                "duration_s": {
                    "type": "integer"
                },
                "end": {
                    "$ref": "#/definitions/model.LatLng"
                },
                "instruction": {
                    "type": "string"
                },
                "maneuver": {
                    "type": "string"
                },
                "polyline": {
                    "type": "string"
                },
                "start": {
                    "$ref": "#/definitions/model.LatLng"
                },
                "travel_mode": {
                    "type": "string"
                }
            }
        },
        "model.Trip": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "computed_at": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "roundtrip": {
                    "type": "boolean"
                },
                "trips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripRoute"
                    }
                },
                "vehicle": {
                    "type": "string",
                    "example": "car"
                },
                "waypoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripStop"
                    }
                }
            }
        },
        "model.TripLeg": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "duration": {
                    "type": "number"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripStep"
                    }
                },
                "summary": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "model.TripRoute": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "duration": {
                    "type": "number"
                },
                "geometry": {
                    "type": "string"
                },
                "legs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TripLeg"
                    }
                },
                "weight": {
                    "type": "number"
                },
                "weight_name": {
                    "type": "string"
                }
            }
        },
        "model.TripStep": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "duration": {
                    "type": "number"
                },
                "geometry": {
                    "type": "string"
                },
                "instruction": {
                    "type": "string"
                },
                "maneuver": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "model.TripStop": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "location": {
                    "$ref": "#/definitions/model.LatLng"
                },
                "place_id": {
                    "type": "string"
                },
                "trips_index": {
                    "type": "integer"
                },
                "waypoint_index": {
                    "type": "integer"
                }
            }
        },
        "response.AdministrativeCompound": {
            "type": "object",
            "properties": {
                "commune": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                }
            }
        },
        "response.AutocompleteResponse": {
            "type": "object",
            "properties": {
                "predictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PlacePrediction"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.LatLng": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "response.PlaceDetail": {
            "type": "object",
            "properties": {
                "compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_description": {
                    "type": "string"
                },
                "formatted_address": {
                    "type": "string"
                },
                "geometry": {
                    "$ref": "#/definitions/response.PlaceGeometry"
                },
                "name": {
                    "type": "string"
                },
                "place_id": {
                    "type": "string"
                }
            }
        },
        "response.PlaceDetailResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/response.PlaceDetail"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.PlaceGeometry": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/response.LatLng"
                }
            }
        },
        "response.PlacePrediction": {
            "type": "object",
            "properties": {
                "compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_compound": {
                    "$ref": "#/definitions/response.AdministrativeCompound"
                },
                "deprecated_description": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "place_id": {
                    "type": "string"
                },
                "structured_formatting": {
                    "$ref": "#/definitions/response.StructuredFormatting"
                }
            }
        },
        "response.StructuredFormatting": {
            "type": "object",
            "properties": {
                "main_text": {
                    "type": "string"
                },
                "secondary_text": {
                    "type": "string"
                }
            }
        },
        "share.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid input"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Road To Destination API Document",
	Description:      "API Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
